using Dms.SharedKernel;
using Dms.Storage.Contracts;

namespace Dms.Storage.Domain;

public enum StorageObjectPurpose
{
    Original,
    Rendition,
    ExtractedText,
}

/// <summary>
/// One immutable blob in object storage. The bytes never change after staging; only the lifecycle
/// status and the scan result do. The object key is generated by the server, never derived from
/// the uploaded filename, so a crafted name cannot escape its prefix.
/// </summary>
public sealed class StorageObject : AggregateRoot<StorageObjectId>
{
    private StorageObject()
    {
    }

    private StorageObject(
        StorageObjectId id,
        string provider,
        string bucket,
        string objectKey,
        StorageObjectPurpose purpose,
        string originalFileName,
        string detectedMimeType,
        string? declaredMimeType,
        long size,
        byte[] sha256,
        ScanStatus scanStatus,
        UserId? createdBy,
        DateTimeOffset now)
        : base(id)
    {
        Provider = provider;
        Bucket = bucket;
        ObjectKey = objectKey;
        Purpose = purpose;
        OriginalFileName = originalFileName;
        DetectedMimeType = detectedMimeType;
        DeclaredMimeType = declaredMimeType;
        Size = size;
        Sha256 = sha256;
        Status = StorageObjectStatus.Staged;
        ScanStatus = scanStatus;
        CreatedBy = createdBy;
        CreatedAt = now;
    }

    public string Provider { get; private set; } = string.Empty;

    public string Bucket { get; private set; } = string.Empty;

    public string ObjectKey { get; private set; } = string.Empty;

    public StorageObjectPurpose Purpose { get; private set; }

    public string OriginalFileName { get; private set; } = string.Empty;

    /// <summary>Sniffed from the leading bytes. The client's claim is recorded but never trusted.</summary>
    public string DetectedMimeType { get; private set; } = "application/octet-stream";

    public string? DeclaredMimeType { get; private set; }

    public long Size { get; private set; }

    public byte[] Sha256 { get; private set; } = [];

    public StorageObjectStatus Status { get; private set; }

    public ScanStatus ScanStatus { get; private set; }

    public DateTimeOffset? ScannedAt { get; private set; }

    public UserId? CreatedBy { get; private set; }

    public DateTimeOffset CreatedAt { get; private set; }

    public DateTimeOffset? CommittedAt { get; private set; }

    public DateTimeOffset? DeletedAt { get; private set; }

    public static StorageObject Stage(
        StorageObjectId id,
        string provider,
        string bucket,
        string objectKey,
        StorageObjectPurpose purpose,
        string originalFileName,
        string detectedMimeType,
        string? declaredMimeType,
        long size,
        byte[] sha256,
        ScanStatus initialScanStatus,
        UserId? createdBy,
        DateTimeOffset now)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(objectKey);
        if (sha256.Length != 32)
        {
            throw new ArgumentException("A SHA-256 digest is 32 bytes.", nameof(sha256));
        }

        return new StorageObject(
            id,
            provider,
            bucket,
            objectKey,
            purpose,
            originalFileName,
            detectedMimeType,
            declaredMimeType,
            size,
            sha256,
            initialScanStatus,
            createdBy,
            now);
    }

    public Result Commit(DateTimeOffset now)
    {
        switch (Status)
        {
            case StorageObjectStatus.Committed:
                return Result.Success();
            case StorageObjectStatus.Staged:
                Status = StorageObjectStatus.Committed;
                CommittedAt = now;
                return Result.Success();
            default:
                return Result.Failure(Error.Conflict(
                    "storage.not_committable",
                    $"A {Status} object cannot be attached to a document."));
        }
    }

    public void RecordScanResult(ScanStatus result, DateTimeOffset now)
    {
        ScanStatus = result;
        ScannedAt = now;
        if (result == ScanStatus.Infected)
        {
            Status = StorageObjectStatus.Quarantined;
        }
    }

    public void MarkForDeletion() => Status = StorageObjectStatus.PendingDeletion;

    /// <summary>The row survives deletion as a tombstone: the hash stays available for audit.</summary>
    public void MarkDeleted(DateTimeOffset now)
    {
        Status = StorageObjectStatus.Deleted;
        DeletedAt = now;
    }

    public StorageObjectInfo ToInfo() =>
        new(Id, OriginalFileName, DetectedMimeType, Size, Sha256, Status, ScanStatus, CreatedBy);
}
