// <auto-generated />
using System;
using Dms.Documents.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dms.Documents.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DocumentsDbContext))]
    [Migration("20260927195845_RecordManagement")]
    partial class RecordManagement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("documents")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "ltree");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Dms.Documents.Domain.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<int>("Depth")
                        .HasColumnType("integer")
                        .HasColumnName("depth");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("ltree")
                        .HasColumnName("path");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Path")
                        .HasDatabaseName("ix_categories_path");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Path"), "gist");

                    b.HasIndex("ParentId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ux_categories_parent_code");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("ParentId", "Code"), false);

                    b.HasIndex("ParentId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_categories_parent_name");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("ParentId", "Name"), false);

                    b.ToTable("categories", "documents", t =>
                        {
                            t.HasCheckConstraint("ck_categories_depth", "depth BETWEEN 0 AND 12");

                            t.HasCheckConstraint("ck_categories_not_own_parent", "parent_id <> id");
                        });
                });

            modelBuilder.Entity("Dms.Documents.Domain.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid?>("CurrentVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_version_id");

                    b.Property<string>("DeleteReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("delete_reason");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<Guid>("DocumentTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_type_id");

                    b.Property<Guid?>("EffectiveVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("effective_version_id");

                    b.Property<int>("LatestVersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("latest_version_number");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_documents_category")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_documents_trash")
                        .HasFilter("deleted_at IS NOT NULL");

                    b.HasIndex("DocumentTypeId")
                        .HasDatabaseName("ix_documents_type")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_documents_owner")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("Title")
                        .HasDatabaseName("ix_documents_title_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Title"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Title"), new[] { "gin_trgm_ops" });

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("ix_documents_updated_at")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("documents", "documents", t =>
                        {
                            t.HasCheckConstraint("ck_documents_deleted_consistent", "(deleted_at IS NULL) = (deleted_by IS NULL)");

                            t.HasCheckConstraint("ck_documents_latest_version", "latest_version_number >= 0");
                        });
                });

            modelBuilder.Entity("Dms.Documents.Domain.DocumentTag", b =>
                {
                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_id");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.Property<Guid>("AddedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("added_by");

                    b.HasKey("DocumentId", "TagId");

                    b.HasIndex("TagId")
                        .HasDatabaseName("ix_document_tags_tag");

                    b.ToTable("document_tags", "documents");
                });

            modelBuilder.Entity("Dms.Documents.Domain.DocumentVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("approval_status");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<string>("ChangeDescription")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("change_description");

                    b.Property<string>("ChangeKind")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("change_kind");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<Guid>("DocumentTypeVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_type_version_id");

                    b.Property<string>("DynamicData")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("dynamic_data");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("mime_type");

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("revision_number");

                    b.Property<byte[]>("Sha256")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("sha256");

                    b.Property<Guid>("StorageObjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("storage_object_id");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.HasKey("Id");

                    b.HasIndex("DynamicData")
                        .HasDatabaseName("ix_document_versions_dynamic_data");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("DynamicData"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("DynamicData"), new[] { "jsonb_path_ops" });

                    b.HasIndex("Sha256")
                        .HasDatabaseName("ix_document_versions_sha256");

                    b.HasIndex("StorageObjectId")
                        .HasDatabaseName("ix_document_versions_storage_object");

                    b.HasIndex("DocumentId", "VersionNumber", "RevisionNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_document_versions_number");

                    b.ToTable("document_versions", "documents", t =>
                        {
                            t.HasCheckConstraint("ck_document_versions_number", "version_number > 0 AND revision_number > 0");

                            t.HasCheckConstraint("ck_document_versions_sha256", "octet_length(sha256) = 32");

                            t.HasCheckConstraint("ck_document_versions_size", "file_size >= 0");
                        });
                });

            modelBuilder.Entity("Dms.Documents.Domain.ManagedRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("DeclaredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("declared_at");

                    b.Property<Guid>("DeclaredBy")
                        .HasColumnType("uuid")
                        .HasColumnName("declared_by");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<Guid>("FinalVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("final_version_id");

                    b.Property<string>("LastTransitionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("last_transition_reason");

                    b.Property<DateTimeOffset>("MetadataFrozenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("metadata_frozen_at");

                    b.Property<Guid>("RecordClassId")
                        .HasColumnType("uuid")
                        .HasColumnName("record_class_id");

                    b.Property<Guid?>("RecordSeriesId")
                        .HasColumnType("uuid")
                        .HasColumnName("record_series_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId")
                        .IsUnique()
                        .HasDatabaseName("ux_records_document");

                    b.HasIndex("FinalVersionId");

                    b.HasIndex("RecordClassId")
                        .HasDatabaseName("ix_records_class");

                    b.HasIndex("RecordSeriesId");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_records_status");

                    b.ToTable("records", "documents", t =>
                        {
                            t.HasCheckConstraint("ck_records_status", "status IN ('Active','UnderRetention','Expired','PendingDisposal','Destroyed')");
                        });
                });

            modelBuilder.Entity("Dms.Documents.Domain.RecordClass", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_record_classes_code");

                    b.ToTable("record_classes", "documents");
                });

            modelBuilder.Entity("Dms.Documents.Domain.RecordSeries", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("RecordClassId")
                        .HasColumnType("uuid")
                        .HasColumnName("record_class_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("RecordClassId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ux_record_series_class_code");

                    b.ToTable("record_series", "documents");
                });

            modelBuilder.Entity("Dms.Documents.Domain.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ux_tags_normalized_name");

                    b.ToTable("tags", "documents");
                });

            modelBuilder.Entity("Dms.Documents.Domain.Category", b =>
                {
                    b.HasOne("Dms.Documents.Domain.Category", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_categories_parent");
                });

            modelBuilder.Entity("Dms.Documents.Domain.Document", b =>
                {
                    b.HasOne("Dms.Documents.Domain.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_documents_category");
                });

            modelBuilder.Entity("Dms.Documents.Domain.DocumentTag", b =>
                {
                    b.HasOne("Dms.Documents.Domain.Document", null)
                        .WithMany("Tags")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_document_tags_document");

                    b.HasOne("Dms.Documents.Domain.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_document_tags_tag");
                });

            modelBuilder.Entity("Dms.Documents.Domain.DocumentVersion", b =>
                {
                    b.HasOne("Dms.Documents.Domain.Document", null)
                        .WithMany("Versions")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_document_versions_document");
                });

            modelBuilder.Entity("Dms.Documents.Domain.ManagedRecord", b =>
                {
                    b.HasOne("Dms.Documents.Domain.Document", null)
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_records_document");

                    b.HasOne("Dms.Documents.Domain.DocumentVersion", null)
                        .WithMany()
                        .HasForeignKey("FinalVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_records_final_version");

                    b.HasOne("Dms.Documents.Domain.RecordClass", null)
                        .WithMany()
                        .HasForeignKey("RecordClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_records_class");

                    b.HasOne("Dms.Documents.Domain.RecordSeries", null)
                        .WithMany()
                        .HasForeignKey("RecordSeriesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_records_series");
                });

            modelBuilder.Entity("Dms.Documents.Domain.RecordSeries", b =>
                {
                    b.HasOne("Dms.Documents.Domain.RecordClass", null)
                        .WithMany()
                        .HasForeignKey("RecordClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_record_series_class");
                });

            modelBuilder.Entity("Dms.Documents.Domain.Document", b =>
                {
                    b.Navigation("Tags");

                    b.Navigation("Versions");
                });
#pragma warning restore 612, 618
        }
    }
}
