// <auto-generated />
using System;
using Dms.Documents.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dms.Documents.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DocumentsDbContext))]
    partial class DocumentsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("documents")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "ltree");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Dms.Documents.Domain.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<int>("Depth")
                        .HasColumnType("integer")
                        .HasColumnName("depth");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("ltree")
                        .HasColumnName("path");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Path")
                        .HasDatabaseName("ix_categories_path");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Path"), "gist");

                    b.HasIndex("ParentId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ux_categories_parent_code");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("ParentId", "Code"), false);

                    b.HasIndex("ParentId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_categories_parent_name");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("ParentId", "Name"), false);

                    b.ToTable("categories", "documents", t =>
                        {
                            t.HasCheckConstraint("ck_categories_depth", "depth BETWEEN 0 AND 12");

                            t.HasCheckConstraint("ck_categories_not_own_parent", "parent_id <> id");
                        });
                });

            modelBuilder.Entity("Dms.Documents.Domain.ClassificationLevel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("Rank")
                        .HasColumnType("integer")
                        .HasColumnName("rank");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_classification_levels_code");

                    b.ToTable("classification_levels", "documents");
                });

            modelBuilder.Entity("Dms.Documents.Domain.DestructionCertificate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<Guid>("ApprovedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by");

                    b.Property<byte[]>("CertificateHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("certificate_hash");

                    b.Property<string>("CertificateNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("certificate_number");

                    b.Property<byte[]>("ContentSha256")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("content_sha256");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("DestroyedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("destroyed_at");

                    b.Property<Guid>("DestroyedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("destroyed_by");

                    b.Property<Guid>("DispositionId")
                        .HasColumnType("uuid")
                        .HasColumnName("disposition_id");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<Guid>("FinalVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("final_version_id");

                    b.Property<string>("FinalVersionLabel")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("final_version_label");

                    b.Property<DateTimeOffset>("LegalHoldCheckedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("legal_hold_checked_at");

                    b.Property<string>("Reason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("reason");

                    b.Property<Guid>("RecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("record_id");

                    b.Property<string>("RecordTitle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("record_title");

                    b.Property<DateTimeOffset?>("RetentionExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("retention_expires_at");

                    b.Property<Guid?>("RetentionPolicyId")
                        .HasColumnType("uuid")
                        .HasColumnName("retention_policy_id");

                    b.Property<int?>("RetentionPolicyVersion")
                        .HasColumnType("integer")
                        .HasColumnName("retention_policy_version");

                    b.HasKey("Id");

                    b.HasIndex("CertificateNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_destruction_certificates_number");

                    b.HasIndex("DispositionId")
                        .IsUnique()
                        .HasDatabaseName("ux_destruction_certificates_disposition");

                    b.HasIndex("RecordId")
                        .IsUnique()
                        .HasDatabaseName("ux_destruction_certificates_record");

                    b.ToTable("destruction_certificates", "documents", t =>
                        {
                            t.HasCheckConstraint("ck_destruction_certificates_sha256", "octet_length(content_sha256) = 32 AND octet_length(certificate_hash) = 32");
                        });
                });

            modelBuilder.Entity("Dms.Documents.Domain.Disposition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by");

                    b.Property<string>("DecisionReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("decision_reason");

                    b.Property<DateTimeOffset?>("DestroyedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("destroyed_at");

                    b.Property<Guid?>("DestroyedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("destroyed_by");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<Guid>("RecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("record_id");

                    b.Property<string>("RequestReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("request_reason");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<Guid>("RequestedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("requested_by");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<Guid?>("ReviewedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("ix_dispositions_document");

                    b.HasIndex("RecordId")
                        .IsUnique()
                        .HasDatabaseName("ux_dispositions_active_record")
                        .HasFilter("status IN ('PendingReview','Approved')");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_dispositions_status");

                    b.ToTable("dispositions", "documents", t =>
                        {
                            t.HasCheckConstraint("ck_dispositions_status", "status IN ('PendingReview','Approved','Rejected','Destroyed')");
                        });
                });

            modelBuilder.Entity("Dms.Documents.Domain.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid?>("CurrentVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_version_id");

                    b.Property<string>("DeleteReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("delete_reason");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<Guid>("DocumentTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_type_id");

                    b.Property<Guid?>("EffectiveVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("effective_version_id");

                    b.Property<int>("LatestVersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("latest_version_number");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_documents_category")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_documents_trash")
                        .HasFilter("deleted_at IS NOT NULL");

                    b.HasIndex("DocumentTypeId")
                        .HasDatabaseName("ix_documents_type")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_documents_owner")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("Title")
                        .HasDatabaseName("ix_documents_title_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Title"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Title"), new[] { "gin_trgm_ops" });

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("ix_documents_updated_at")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("documents", "documents", t =>
                        {
                            t.HasCheckConstraint("ck_documents_deleted_consistent", "(deleted_at IS NULL) = (deleted_by IS NULL)");

                            t.HasCheckConstraint("ck_documents_latest_version", "latest_version_number >= 0");
                        });
                });

            modelBuilder.Entity("Dms.Documents.Domain.DocumentClassification", b =>
                {
                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<Guid>("AssignedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_by");

                    b.Property<Guid>("LevelId")
                        .HasColumnType("uuid")
                        .HasColumnName("level_id");

                    b.HasKey("DocumentId");

                    b.HasIndex("LevelId")
                        .HasDatabaseName("ix_document_classifications_level");

                    b.ToTable("document_classifications", "documents");
                });

            modelBuilder.Entity("Dms.Documents.Domain.DocumentTag", b =>
                {
                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_id");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.Property<Guid>("AddedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("added_by");

                    b.HasKey("DocumentId", "TagId");

                    b.HasIndex("TagId")
                        .HasDatabaseName("ix_document_tags_tag");

                    b.ToTable("document_tags", "documents");
                });

            modelBuilder.Entity("Dms.Documents.Domain.DocumentVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("approval_status");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<string>("ChangeDescription")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("change_description");

                    b.Property<string>("ChangeKind")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("change_kind");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<Guid>("DocumentTypeVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_type_version_id");

                    b.Property<string>("DynamicData")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("dynamic_data");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("mime_type");

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("revision_number");

                    b.Property<byte[]>("Sha256")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("sha256");

                    b.Property<Guid>("StorageObjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("storage_object_id");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.HasKey("Id");

                    b.HasIndex("DynamicData")
                        .HasDatabaseName("ix_document_versions_dynamic_data");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("DynamicData"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("DynamicData"), new[] { "jsonb_path_ops" });

                    b.HasIndex("Sha256")
                        .HasDatabaseName("ix_document_versions_sha256");

                    b.HasIndex("StorageObjectId")
                        .HasDatabaseName("ix_document_versions_storage_object");

                    b.HasIndex("DocumentId", "VersionNumber", "RevisionNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_document_versions_number");

                    b.ToTable("document_versions", "documents", t =>
                        {
                            t.HasCheckConstraint("ck_document_versions_number", "version_number > 0 AND revision_number > 0");

                            t.HasCheckConstraint("ck_document_versions_sha256", "octet_length(sha256) = 32");

                            t.HasCheckConstraint("ck_document_versions_size", "file_size >= 0");
                        });
                });

            modelBuilder.Entity("Dms.Documents.Domain.ImportItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActualSha256")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("actual_sha256");

                    b.Property<long?>("ActualSize")
                        .HasColumnType("bigint")
                        .HasColumnName("actual_size");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EntryJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("entry_json");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_message");

                    b.Property<string>("ExpectedSha256")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("expected_sha256");

                    b.Property<long?>("ExpectedSize")
                        .HasColumnType("bigint")
                        .HasColumnName("expected_size");

                    b.Property<Guid>("ImportJobId")
                        .HasColumnType("uuid")
                        .HasColumnName("import_job_id");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("source_id");

                    b.Property<string>("SourcePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("source_path");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<Guid?>("TargetDocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_document_id");

                    b.Property<Guid?>("TargetRecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_record_id");

                    b.Property<Guid?>("TargetVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_version_id");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_import_items_claimable")
                        .HasFilter("status IN ('Ready','Retryable','Running')");

                    b.HasIndex("ImportJobId", "SourceId")
                        .IsUnique()
                        .HasDatabaseName("ux_import_items_job_source");

                    b.HasIndex("ImportJobId", "Status")
                        .HasDatabaseName("ix_import_items_job_status");

                    b.ToTable("import_items", "documents", t =>
                        {
                            t.HasCheckConstraint("ck_import_items_status", "status IN ('Pending','Valid','Invalid','Ready','Running','Succeeded','Failed','Skipped','Retryable')");
                        });
                });

            modelBuilder.Entity("Dms.Documents.Domain.ImportJob", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("BytesProcessed")
                        .HasColumnType("bigint")
                        .HasColumnName("bytes_processed");

                    b.Property<long>("BytesTotal")
                        .HasColumnType("bigint")
                        .HasColumnName("bytes_total");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<bool>("CreateMissingCategories")
                        .HasColumnType("boolean")
                        .HasColumnName("create_missing_categories");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<bool>("DryRunOnly")
                        .HasColumnType("boolean")
                        .HasColumnName("dry_run_only");

                    b.Property<int>("FailedItems")
                        .HasColumnType("integer")
                        .HasColumnName("failed_items");

                    b.Property<string>("FailurePolicy")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("failure_policy");

                    b.Property<string>("FilesRoot")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("files_root");

                    b.Property<int>("InvalidItems")
                        .HasColumnType("integer")
                        .HasColumnName("invalid_items");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<string>("ManifestSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("manifest_sha256");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("ProcessedItems")
                        .HasColumnType("integer")
                        .HasColumnName("processed_items");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int>("SkippedItems")
                        .HasColumnType("integer")
                        .HasColumnName("skipped_items");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("source_system");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<int>("SucceededItems")
                        .HasColumnType("integer")
                        .HasColumnName("succeeded_items");

                    b.Property<int>("TotalItems")
                        .HasColumnType("integer")
                        .HasColumnName("total_items");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_import_jobs_created_at");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_import_jobs_status");

                    b.HasIndex("SourceSystem", "CreatedAt")
                        .HasDatabaseName("ix_import_jobs_source_created");

                    b.ToTable("import_jobs", "documents", t =>
                        {
                            t.HasCheckConstraint("ck_import_jobs_failure_policy", "failure_policy IN ('ContinueOnError','StopOnError')");

                            t.HasCheckConstraint("ck_import_jobs_status", "status IN ('Created','Validating','ValidationFailed','Ready','Running','Paused','Completed','CompletedWithErrors','Failed')");
                        });
                });

            modelBuilder.Entity("Dms.Documents.Domain.ImportMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid?>("ImportJobId")
                        .HasColumnType("uuid")
                        .HasColumnName("import_job_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("source_key");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("source_system");

                    b.Property<string>("TargetKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("target_key");

                    b.HasKey("Id");

                    b.HasIndex("ImportJobId");

                    b.HasIndex("SourceSystem", "ImportJobId", "Kind", "SourceKey")
                        .IsUnique()
                        .HasDatabaseName("ux_import_mappings_lookup");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("SourceSystem", "ImportJobId", "Kind", "SourceKey"), false);

                    b.ToTable("import_mappings", "documents");
                });

            modelBuilder.Entity("Dms.Documents.Domain.ImportSourceIndex", b =>
                {
                    b.Property<string>("SourceSystem")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("source_system");

                    b.Property<string>("SourceId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("source_id");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<Guid>("ImportItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("import_item_id");

                    b.Property<Guid>("ImportJobId")
                        .HasColumnType("uuid")
                        .HasColumnName("import_job_id");

                    b.Property<DateTimeOffset>("ImportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("imported_at");

                    b.HasKey("SourceSystem", "SourceId");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("ix_import_source_index_document");

                    b.ToTable("import_source_index", "documents");
                });

            modelBuilder.Entity("Dms.Documents.Domain.LegalHold", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("reason");

                    b.Property<string>("ReleaseReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("release_reason");

                    b.Property<DateTimeOffset?>("ReleasedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("released_at");

                    b.Property<Guid?>("ReleasedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("released_by");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("ix_legal_holds_document");

                    b.HasIndex("DocumentId", "ReleasedAt")
                        .HasDatabaseName("ix_legal_holds_active")
                        .HasFilter("released_at IS NULL");

                    b.ToTable("legal_holds", "documents");
                });

            modelBuilder.Entity("Dms.Documents.Domain.ManagedRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("DeclaredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("declared_at");

                    b.Property<Guid>("DeclaredBy")
                        .HasColumnType("uuid")
                        .HasColumnName("declared_by");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<Guid>("FinalVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("final_version_id");

                    b.Property<string>("LastTransitionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("last_transition_reason");

                    b.Property<DateTimeOffset>("MetadataFrozenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("metadata_frozen_at");

                    b.Property<Guid>("RecordClassId")
                        .HasColumnType("uuid")
                        .HasColumnName("record_class_id");

                    b.Property<Guid?>("RecordSeriesId")
                        .HasColumnType("uuid")
                        .HasColumnName("record_series_id");

                    b.Property<string>("RetentionExceptionReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("retention_exception_reason");

                    b.Property<DateTimeOffset?>("RetentionExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("retention_expires_at");

                    b.Property<int?>("RetentionPeriodDays")
                        .HasColumnType("integer")
                        .HasColumnName("retention_period_days");

                    b.Property<Guid?>("RetentionPolicyId")
                        .HasColumnType("uuid")
                        .HasColumnName("retention_policy_id");

                    b.Property<int?>("RetentionPolicyVersion")
                        .HasColumnType("integer")
                        .HasColumnName("retention_policy_version");

                    b.Property<string>("RetentionStartEvent")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("retention_start_event");

                    b.Property<DateTimeOffset?>("RetentionStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("retention_started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId")
                        .IsUnique()
                        .HasDatabaseName("ux_records_document");

                    b.HasIndex("FinalVersionId");

                    b.HasIndex("RecordClassId")
                        .HasDatabaseName("ix_records_class");

                    b.HasIndex("RecordSeriesId");

                    b.HasIndex("RetentionExpiresAt")
                        .HasDatabaseName("ix_records_retention_expires")
                        .HasFilter("retention_expires_at IS NOT NULL");

                    b.HasIndex("RetentionPolicyId");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_records_status");

                    b.ToTable("records", "documents", t =>
                        {
                            t.HasCheckConstraint("ck_records_status", "status IN ('Active','UnderRetention','Expired','PendingDisposal','Destroyed')");
                        });
                });

            modelBuilder.Entity("Dms.Documents.Domain.RecordClass", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_record_classes_code");

                    b.ToTable("record_classes", "documents");
                });

            modelBuilder.Entity("Dms.Documents.Domain.RecordSeries", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("RecordClassId")
                        .HasColumnType("uuid")
                        .HasColumnName("record_class_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("RecordClassId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ux_record_series_class_code");

                    b.ToTable("record_series", "documents");
                });

            modelBuilder.Entity("Dms.Documents.Domain.RetentionPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("RetentionPeriodDays")
                        .HasColumnType("integer")
                        .HasColumnName("retention_period_days");

                    b.Property<string>("StartEvent")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("start_event");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_retention_policies_code");

                    b.ToTable("retention_policies", "documents", t =>
                        {
                            t.HasCheckConstraint("ck_retention_policies_days", "retention_period_days > 0");

                            t.HasCheckConstraint("ck_retention_policies_version", "version_number > 0");
                        });
                });

            modelBuilder.Entity("Dms.Documents.Domain.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ux_tags_normalized_name");

                    b.ToTable("tags", "documents");
                });

            modelBuilder.Entity("Dms.Documents.Domain.Category", b =>
                {
                    b.HasOne("Dms.Documents.Domain.Category", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_categories_parent");
                });

            modelBuilder.Entity("Dms.Documents.Domain.DestructionCertificate", b =>
                {
                    b.HasOne("Dms.Documents.Domain.Disposition", null)
                        .WithMany()
                        .HasForeignKey("DispositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_destruction_certificates_disposition");

                    b.HasOne("Dms.Documents.Domain.ManagedRecord", null)
                        .WithMany()
                        .HasForeignKey("RecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_destruction_certificates_record");
                });

            modelBuilder.Entity("Dms.Documents.Domain.Disposition", b =>
                {
                    b.HasOne("Dms.Documents.Domain.Document", null)
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_dispositions_document");

                    b.HasOne("Dms.Documents.Domain.ManagedRecord", null)
                        .WithMany()
                        .HasForeignKey("RecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_dispositions_record");
                });

            modelBuilder.Entity("Dms.Documents.Domain.Document", b =>
                {
                    b.HasOne("Dms.Documents.Domain.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_documents_category");
                });

            modelBuilder.Entity("Dms.Documents.Domain.DocumentClassification", b =>
                {
                    b.HasOne("Dms.Documents.Domain.Document", null)
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_document_classifications_document");

                    b.HasOne("Dms.Documents.Domain.ClassificationLevel", null)
                        .WithMany()
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_document_classifications_level");
                });

            modelBuilder.Entity("Dms.Documents.Domain.DocumentTag", b =>
                {
                    b.HasOne("Dms.Documents.Domain.Document", null)
                        .WithMany("Tags")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_document_tags_document");

                    b.HasOne("Dms.Documents.Domain.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_document_tags_tag");
                });

            modelBuilder.Entity("Dms.Documents.Domain.DocumentVersion", b =>
                {
                    b.HasOne("Dms.Documents.Domain.Document", null)
                        .WithMany("Versions")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_document_versions_document");
                });

            modelBuilder.Entity("Dms.Documents.Domain.ImportItem", b =>
                {
                    b.HasOne("Dms.Documents.Domain.ImportJob", null)
                        .WithMany()
                        .HasForeignKey("ImportJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_import_items_job");
                });

            modelBuilder.Entity("Dms.Documents.Domain.ImportMapping", b =>
                {
                    b.HasOne("Dms.Documents.Domain.ImportJob", null)
                        .WithMany()
                        .HasForeignKey("ImportJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_import_mappings_job");
                });

            modelBuilder.Entity("Dms.Documents.Domain.LegalHold", b =>
                {
                    b.HasOne("Dms.Documents.Domain.Document", null)
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_legal_holds_document");
                });

            modelBuilder.Entity("Dms.Documents.Domain.ManagedRecord", b =>
                {
                    b.HasOne("Dms.Documents.Domain.Document", null)
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_records_document");

                    b.HasOne("Dms.Documents.Domain.DocumentVersion", null)
                        .WithMany()
                        .HasForeignKey("FinalVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_records_final_version");

                    b.HasOne("Dms.Documents.Domain.RecordClass", null)
                        .WithMany()
                        .HasForeignKey("RecordClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_records_class");

                    b.HasOne("Dms.Documents.Domain.RecordSeries", null)
                        .WithMany()
                        .HasForeignKey("RecordSeriesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_records_series");

                    b.HasOne("Dms.Documents.Domain.RetentionPolicy", null)
                        .WithMany()
                        .HasForeignKey("RetentionPolicyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_records_retention_policy");
                });

            modelBuilder.Entity("Dms.Documents.Domain.RecordSeries", b =>
                {
                    b.HasOne("Dms.Documents.Domain.RecordClass", null)
                        .WithMany()
                        .HasForeignKey("RecordClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_record_series_class");
                });

            modelBuilder.Entity("Dms.Documents.Domain.Document", b =>
                {
                    b.Navigation("Tags");

                    b.Navigation("Versions");
                });
#pragma warning restore 612, 618
        }
    }
}
