<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>Dms.Host</RootNamespace>
    <UserSecretsId>dms-host</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BuildingBlocks\Dms.Infrastructure\Dms.Infrastructure.csproj" />
    <ProjectReference Include="..\BuildingBlocks\Dms.Web\Dms.Web.csproj" />
    <ProjectReference Include="..\Modules\Audit\Dms.Audit.Infrastructure\Dms.Audit.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\Authorization\Dms.Authorization.Infrastructure\Dms.Authorization.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\Identity\Dms.Identity.Infrastructure\Dms.Identity.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\Storage\Dms.Storage.Infrastructure\Dms.Storage.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\DocumentTypes\Dms.DocumentTypes.Infrastructure\Dms.DocumentTypes.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\Documents\Dms.Documents.Infrastructure\Dms.Documents.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\Workflow\Dms.Workflow.Infrastructure\Dms.Workflow.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\Search\Dms.Search.Infrastructure\Dms.Search.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Scalar.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Dms.IntegrationTests" />
  </ItemGroup>

</Project>
