/* Generated by frontend/scripts/capture-guide.mjs. Arrow positions are percentages of each photo. */
export type GuideArrowFrom = 'top' | 'bottom' | 'left' | 'right';

export type GuideArrow = {
  label: string;
  x: number;
  y: number;
  from: GuideArrowFrom;
};

export const guideShotLayout: Record<string, { arrows: GuideArrow[] }> = {
  "start-login": {
    "arrows": [
      {
        "label": "نام کاربری",
        "x": 25,
        "y": 50.2,
        "from": "top"
      },
      {
        "label": "گذرواژه",
        "x": 25,
        "y": 57.5,
        "from": "top"
      },
      {
        "label": "ورود",
        "x": 25,
        "y": 62.5,
        "from": "right"
      }
    ]
  },
  "start-home": {
    "arrows": [
      {
        "label": "نشان سیستم",
        "x": 89.7,
        "y": 3,
        "from": "left"
      },
      {
        "label": "جستجو",
        "x": 89.7,
        "y": 7.7,
        "from": "left"
      },
      {
        "label": "سند جدید",
        "x": 89.7,
        "y": 23.8,
        "from": "left"
      },
      {
        "label": "کارتابل",
        "x": 89.7,
        "y": 28.3,
        "from": "left"
      },
      {
        "label": "تنظیمات",
        "x": 89.7,
        "y": 92.7,
        "from": "left"
      }
    ]
  },
  "browse-list": {
    "arrows": [
      {
        "label": "درخت پوشه‌ها",
        "x": 88.7,
        "y": 54.7,
        "from": "left"
      },
      {
        "label": "فیلتر عنوان",
        "x": 44.4,
        "y": 17.4,
        "from": "top"
      },
      {
        "label": "فهرست اسناد",
        "x": 44.3,
        "y": 27.9,
        "from": "top"
      },
      {
        "label": "سند جدید",
        "x": 5,
        "y": 10.2,
        "from": "right"
      }
    ]
  },
  "create-form": {
    "arrows": [
      {
        "label": "انتخاب فایل",
        "x": 39.7,
        "y": 17.6,
        "from": "top"
      },
      {
        "label": "پوشه",
        "x": 52.5,
        "y": 34.2,
        "from": "top"
      },
      {
        "label": "نوع سند",
        "x": 26.9,
        "y": 34.2,
        "from": "top"
      },
      {
        "label": "مشخصات",
        "x": 39.7,
        "y": 60.9,
        "from": "top"
      },
      {
        "label": "ثبت سند",
        "x": 17.8,
        "y": 72.3,
        "from": "top"
      }
    ]
  },
  "search-results": {
    "arrows": [
      {
        "label": "عبارت جستجو",
        "x": 43.9,
        "y": 20.4,
        "from": "top"
      },
      {
        "label": "جستجو در متن فایل",
        "x": 40.4,
        "y": 27.3,
        "from": "left"
      },
      {
        "label": "تعداد تکرار",
        "x": 50.9,
        "y": 41.7,
        "from": "top"
      },
      {
        "label": "هایلایت",
        "x": 72.8,
        "y": 43.7,
        "from": "top"
      },
      {
        "label": "فیلتر پوشه",
        "x": 13.5,
        "y": 35.4,
        "from": "right"
      }
    ]
  },
  "document-view": {
    "arrows": [
      {
        "label": "افزودن نسخه",
        "x": 29.7,
        "y": 11.3,
        "from": "bottom"
      },
      {
        "label": "حذف",
        "x": 7.9,
        "y": 11.3,
        "from": "right"
      },
      {
        "label": "پیش‌نمایش",
        "x": 43.1,
        "y": 37.8,
        "from": "top"
      },
      {
        "label": "تاریخچه نسخه‌ها",
        "x": 40.9,
        "y": 94.6,
        "from": "top"
      }
    ]
  },
  "document-share": {
    "arrows": [
      {
        "label": "اشتراک‌گذاری",
        "x": 8.9,
        "y": 68.7,
        "from": "right"
      },
      {
        "label": "پیوند بیرونی",
        "x": 71.3,
        "y": 80.2,
        "from": "top"
      },
      {
        "label": "گیرنده",
        "x": 73.6,
        "y": 73.7,
        "from": "left"
      }
    ]
  },
  "tasks-inbox": {
    "arrows": [
      {
        "label": "کارتابل",
        "x": 89.7,
        "y": 28.3,
        "from": "left"
      },
      {
        "label": "کار باز",
        "x": 72.6,
        "y": 15.4,
        "from": "top"
      },
      {
        "label": "تأیید",
        "x": 10.4,
        "y": 17.3,
        "from": "right"
      },
      {
        "label": "رد",
        "x": 6.9,
        "y": 17.3,
        "from": "bottom"
      }
    ]
  },
  "share-inbox": {
    "arrows": [
      {
        "label": "اشتراک‌شده با من",
        "x": 89.7,
        "y": 36.9,
        "from": "left"
      },
      {
        "label": "سند اشتراک‌شده",
        "x": 72.6,
        "y": 15.4,
        "from": "top"
      }
    ]
  },
  "recycle-bin": {
    "arrows": [
      {
        "label": "سطل بازیافت",
        "x": 89.7,
        "y": 41.3,
        "from": "left"
      },
      {
        "label": "سند حذف‌شده",
        "x": 46.2,
        "y": 14.7,
        "from": "top"
      },
      {
        "label": "بازگردانی",
        "x": 5.3,
        "y": 15.5,
        "from": "right"
      }
    ]
  },
  "admin-folders": {
    "arrows": [
      {
        "label": "تنظیمات",
        "x": 89.7,
        "y": 92.7,
        "from": "left"
      },
      {
        "label": "تب پوشه‌ها",
        "x": 58.4,
        "y": 9.5,
        "from": "bottom"
      },
      {
        "label": "دسترسی‌ها",
        "x": 5.8,
        "y": 24.6,
        "from": "right"
      }
    ]
  },
  "admin-ocr": {
    "arrows": [
      {
        "label": "تب جستجو و نمایه",
        "x": 36.3,
        "y": 9.5,
        "from": "bottom"
      },
      {
        "label": "فایل‌های OCR",
        "x": 68.6,
        "y": 22.4,
        "from": "top"
      },
      {
        "label": "خطای استخراج",
        "x": 67.3,
        "y": 85.3,
        "from": "top"
      }
    ]
  }
};
