// <auto-generated />
using System;
using Dms.Authorization.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dms.Authorization.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AuthorizationDbContext))]
    partial class AuthorizationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("authz")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Dms.Authorization.Domain.ResourcePermissionEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Effect")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("effect");

                    b.Property<bool>("Inherit")
                        .HasColumnType("boolean")
                        .HasColumnName("inherit");

                    b.Property<string>("PermissionCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("permission_code");

                    b.Property<string>("Reason")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("reason");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource_id");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("resource_type");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.Property<string>("SubjectType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("subject_type");

                    b.HasKey("Id");

                    b.HasIndex("PermissionCode");

                    b.HasIndex("ResourceType", "ResourceId")
                        .HasDatabaseName("ix_resource_permissions_resource");

                    b.HasIndex("SubjectType", "SubjectId")
                        .HasDatabaseName("ix_resource_permissions_subject");

                    b.HasIndex("ResourceType", "ResourceId", "SubjectType", "SubjectId", "PermissionCode")
                        .IsUnique()
                        .HasDatabaseName("ux_resource_permissions_tuple");

                    b.ToTable("resource_permissions", "authz", t =>
                        {
                            t.HasCheckConstraint("ck_resource_permissions_inherit", "inherit = false OR resource_type = 'Category'");
                        });
                });

            modelBuilder.Entity("Dms.Authorization.Domain.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("description");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_roles_code");

                    b.ToTable("roles", "authz");
                });

            modelBuilder.Entity("Dms.Authorization.Domain.UserRoleAssignment", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<DateTimeOffset>("GrantedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at");

                    b.Property<Guid>("GrantedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("granted_by");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_roles_role");

                    b.ToTable("user_roles", "authz");
                });

            modelBuilder.Entity("Dms.Authorization.Infrastructure.Persistence.PermissionRecord", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("description");

                    b.Property<bool>("RequiresView")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_view");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("scope");

                    b.HasKey("Code");

                    b.ToTable("permissions", "authz");
                });

            modelBuilder.Entity("Dms.Authorization.Domain.ResourcePermissionEntry", b =>
                {
                    b.HasOne("Dms.Authorization.Infrastructure.Persistence.PermissionRecord", null)
                        .WithMany()
                        .HasForeignKey("PermissionCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Dms.Authorization.Domain.Role", b =>
                {
                    b.OwnsMany("Dms.Authorization.Domain.RolePermission", "Permissions", b1 =>
                        {
                            b1.Property<Guid>("RoleId")
                                .HasColumnType("uuid")
                                .HasColumnName("role_id");

                            b1.Property<string>("PermissionCode")
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("permission_code");

                            b1.HasKey("RoleId", "PermissionCode");

                            b1.HasIndex("PermissionCode");

                            b1.ToTable("role_permissions", "authz");

                            b1.HasOne("Dms.Authorization.Infrastructure.Persistence.PermissionRecord", null)
                                .WithMany()
                                .HasForeignKey("PermissionCode")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("RoleId");
                        });

                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("Dms.Authorization.Domain.UserRoleAssignment", b =>
                {
                    b.HasOne("Dms.Authorization.Domain.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
