<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Dms.Authorization</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\Dms.Application\Dms.Application.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Dms.SharedKernel\Dms.SharedKernel.csproj" />
    <ProjectReference Include="..\..\Audit\Dms.Audit.Contracts\Dms.Audit.Contracts.csproj" />
    <ProjectReference Include="..\..\Identity\Dms.Identity.Contracts\Dms.Identity.Contracts.csproj" />
    <ProjectReference Include="..\Dms.Authorization.Contracts\Dms.Authorization.Contracts.csproj" />
  </ItemGroup>

</Project>
