import type { FieldType, RuleKind } from '../../lib/api';

/** Administration wording, kept apart from the everyday UI strings. */
export const a = {
  documentTypes: 'انواع سند',
  newType: 'نوع سند جدید',
  name: 'نام',
  code: 'کد',
  codeHelp: 'حروف لاتین بزرگ، ثابت و غیرقابل تغییر؛ مثلاً CONTRACT',
  description: 'توضیحات',
  create: 'ایجاد',
  cancel: 'انصراف',
  save: 'ذخیره',
  saved: 'ذخیره شد.',
  unpublished: 'منتشرنشده',
  inactive: 'غیرفعال',
  active: 'فعال',
  settings: 'تنظیمات',
  saveSettings: 'ذخیره‌ی تنظیمات',
  editPolicy: 'ویرایش مشخصات',
  policyNewRevision: 'هر تغییر، بازنگری تازه (V3.2) می‌سازد',
  policyInPlace: 'تغییر در همان ردیف، با ثبت کامل در ممیزی',
  allowedExtensions: 'پسوندهای مجاز',
  allowedExtensionsHelp: 'خالی یعنی همه. Enter برای افزودن.',
  maxUploadMb: 'حداکثر حجم فایل (مگابایت)',
  retentionDays: 'نگهداری پس از حذف (روز)',
  retentionDaysHelp: 'خالی یعنی حذف قطعی بلافاصله بعد از سطل بازیافت مجاز است.',
  supportsLegalHold: 'پشتیبانی از نگهداری قانونی (Legal hold)',
  draft: 'پیش‌نویس',
  draftHelp: 'تغییرات روی پیش‌نویس ذخیره می‌شود و تا انتشار روی اسناد اثری ندارد.',
  fields: 'فیلدها',
  addField: 'افزودن فیلد',
  rules: 'قواعد',
  addRule: 'افزودن قاعده',
  saveDraft: 'ذخیره‌ی پیش‌نویس',
  publish: 'انتشار',
  publishConfirm:
    'نسخه‌ی منتشرشده دیگر قابل تغییر نیست. اسناد تازه با این نسخه ثبت می‌شوند و اسناد قبلی با نسخه‌ی خودشان خوانده می‌شوند.',
  published: 'منتشر شد.',
  unsaved: 'تغییرات ذخیره‌نشده',
  versions: 'نسخه‌ها',
  preview: 'پیش‌نمایش فرم',
  previewHelp: 'فرم را امتحان کنید؛ قواعد نمایش و الزام همین‌جا اجرا می‌شوند.',
  noFields: 'هنوز فیلدی تعریف نشده است.',
  editField: 'ویرایش فیلد',
  label: 'برچسب',
  labelEn: 'برچسب انگلیسی',
  type: 'نوع',
  required: 'الزامی',
  approvalRelevant: 'مؤثر در تأیید',
  approvalRelevantHelp: 'تغییر این فیلد همیشه بازنگری تازه می‌سازد.',
  searchable: 'قابل جستجو',
  showInList: 'نمایش در فهرست',
  fieldActive: 'فعال',
  helpText: 'راهنما',
  defaultValue: 'مقدار پیش‌فرض (JSON)',
  options: 'گزینه‌ها',
  addOption: 'افزودن گزینه',
  optionValue: 'مقدار',
  optionLabel: 'عنوان',
  minLength: 'حداقل طول',
  maxLength: 'حداکثر طول',
  pattern: 'الگو (Regex)',
  patternMessage: 'پیام خطای الگو',
  min: 'حداقل',
  max: 'حداکثر',
  scale: 'رقم اعشار',
  minDate: 'از تاریخ (yyyy-MM-dd)',
  maxDate: 'تا تاریخ (yyyy-MM-dd)',
  maxItems: 'حداکثر انتخاب',
  remove: 'حذف',
  up: '↑',
  down: '↓',
  ruleKind: 'نوع قاعده',
  targets: 'فیلدهای هدف',
  condition: 'شرط (JSON)',
  assertion: 'ادعا (JSON)',
  message: 'پیام خطا',
  conditionHelp: 'مثال: {"field": "amount", "op": "gt", "value": 10000000000}',
  invalidJson: 'JSON معتبر نیست.',
  unknownField: 'فیلد ناشناخته',
  errors: 'این مشکلات را برطرف کنید:',
  workflows: 'گردش‌های کار',
  newWorkflow: 'گردش کار جدید',
  steps: 'مراحل',
  stepsHelp: 'مراحل با شماره‌ی ترتیب یکسان هم‌زمان اجرا می‌شوند.',
  addStep: 'افزودن مرحله',
  stepName: 'نام مرحله',
  sequence: 'ترتیب',
  sequenceHelp: 'یکسان = موازی',
  slaHours: 'مهلت (ساعت)',
  assignee: 'مسئول',
  assigneeField: 'کد فیلد کاربر',
  assigneeFieldHelp: 'فیلدی از نوع کاربر در مشخصات سند',
  completionRule: 'تکمیل',
  completionAny: 'یک نفر کافی است',
  completionAll: 'همه‌ی اعضا',
  allowSelfApproval: 'تأیید توسط نویسنده مجاز است',
  allowedActions: 'اقدام‌های مجاز',
  returnTarget: 'بازگشت به',
  returnPrevious: 'مرحله‌ی قبل',
  stepCondition: 'شرط ورود (JSON)',
  stepConditionHelp: 'خالی یعنی همیشه. مثال: {"field": "amount", "op": "gt", "value": 10000000000}',
  publishWorkflowConfirm:
    'نسخه‌ی منتشرشده دیگر قابل تغییر نیست. گردش‌های در جریان با نسخه‌ی خودشان ادامه می‌دهند و گردش‌های تازه از این نسخه استفاده می‌کنند.',
  workflowMode: 'گردش کار نسخه‌ها',
  modeNone: 'بدون تأیید',
  modeManual: 'نویسنده برای بررسی می‌فرستد',
  modeAuto: 'هر نسخه‌ی تازه خودکار وارد بررسی می‌شود',
  workflow: 'گردش کار',
} as const;

export const fieldTypeLabels: Record<FieldType, string> = {
  Text: 'متن',
  LongText: 'متن بلند',
  Integer: 'عدد صحیح',
  Decimal: 'عدد اعشاری',
  Boolean: 'بله/خیر',
  Date: 'تاریخ',
  DateTime: 'تاریخ و ساعت',
  Select: 'انتخاب تکی',
  MultiSelect: 'انتخاب چندتایی',
  User: 'کاربر',
  Group: 'گروه',
  DocumentReference: 'ارجاع به سند',
  Url: 'نشانی وب',
  Email: 'رایانامه',
  Phone: 'تلفن',
};

export const ruleKindLabels: Record<RuleKind, string> = {
  Show: 'نمایش مشروط',
  Require: 'الزام مشروط',
  Validate: 'اعتبارسنجی',
};
