import type { SealProblem } from '../../lib/api';

export const a = {
  title: 'رویدادنگاری',
  menu: 'رویدادنگاری',
  from: 'از تاریخ',
  to: 'تا تاریخ (شامل)',
  action: 'رویداد',
  outcome: 'نتیجه',
  actorType: 'نوع انجام‌دهنده',
  user: 'کاربر',
  documentId: 'شناسه‌ی سند',
  any: 'همه',
  apply: 'نمایش',
  more: 'موارد بیشتر',
  empty: 'رویدادی با این شرایط پیدا نشد.',
  badDate: 'تاریخ را به شکل ۱۴۰۳/۰۷/۰۱ وارد کنید.',
  exportNeedsRange: 'برای خروجی گرفتن، بازه‌ی تاریخ را مشخص کنید.',
  exported: 'فایل خروجی آماده شد. خروجی گرفتن هم در رویدادنگاری ثبت می‌شود.',
  document: 'سند',
  entity: 'موضوع',
  version: 'نسخه',
  shareLink: 'پیوند',
  ip: 'نشانی IP',
  userAgent: 'مرورگر',
  correlation: 'شناسه‌ی درخواست',
  outcomes: { SUCCESS: 'موفق', DENIED: 'ردشده', FAILED: 'ناموفق' } as Record<string, string>,
  actorTypes: { USER: 'کاربر', SHARELINK: 'پیوند بیرونی', SYSTEM: 'سامانه', ANONYMOUS: 'ناشناس' } as Record<string, string>,
  seals: 'مهر و موم رویدادنگاری',
  verify: (days: number) => `بررسی سلامت ${days.toLocaleString('fa-IR')} روز اخیر`,
  verifying: 'در حال بررسی…',
  keyed: 'مهر با کلید (HMAC)',
  unkeyed: 'مهر بدون کلید',
  unkeyedHelp:
    'کلید مهر تنظیم نشده است (Dms__Audit__SealKey). تغییرها همچنان آشکار می‌شوند، اما کسی که به پایگاه داده دسترسی نوشتن دارد می‌تواند مهرها را از نو بسازد.',
  sealedUntil: 'مهرشده تا',
  nothingSealed: 'هنوز چیزی مهر نشده',
  sealCount: 'تعداد مهرها',
  lastIntact: 'آخرین بررسی: سالم',
  lastBroken: 'آخرین بررسی: دست‌کاری یافت شد',
  intact: (seals: number, rows: number) =>
    `${seals.toLocaleString('fa-IR')} مهر و ${rows.toLocaleString('fa-IR')} رویداد بررسی شد؛ همه سالم است.`,
  broken: (count: number) => `${count.toLocaleString('fa-IR')} مورد ناسازگاری پیدا شد:`,
  problemKinds: {
    RowsChanged: 'رویدادها تغییر کرده، حذف یا با تاریخ گذشته افزوده شده‌اند',
    ChainBroken: 'زنجیره‌ی مهرها گسسته است',
    SealInvalid: 'خود مهر دست‌کاری شده است',
    UnknownKey: 'کلید این مهر در دسترس نیست',
    RowsBeforeFirstSeal: 'رویدادهایی با تاریخ پیش از نخستین مهر',
  } as Record<SealProblem['kind'], string>,
};
