/** Wording for users, groups, roles, categories and the permission editor. */
export const d = {
  administration: 'مدیریت',
  users: 'کاربران',
  groups: 'گروه‌ها',
  roles: 'نقش‌ها',
  categories: 'پوشه‌ها',
  permissionsTitle: 'دسترسی‌ها',

  search: 'جستجو',
  more: 'موارد بیشتر',
  create: 'ایجاد',
  save: 'ذخیره',
  cancel: 'انصراف',
  close: 'بستن',
  saved: 'ذخیره شد.',
  add: 'افزودن',
  remove: 'حذف',
  edit: 'ویرایش',
  active: 'فعال',
  inactive: 'غیرفعال',
  none: '—',
  name: 'نام',
  code: 'کد',
  codeHelp: 'حروف لاتین، ثابت و غیرقابل تغییر؛ مثلاً FINANCE',
  description: 'توضیحات',
  empty: 'موردی نیست.',

  newUser: 'کاربر جدید',
  username: 'نام کاربری',
  displayName: 'نام نمایشی',
  email: 'رایانامه',
  password: 'گذرواژه‌ی اولیه',
  passwordHelp: 'دست‌کم ۱۲ نویسه. کاربر در نخستین ورود باید آن را عوض کند.',
  mustChangePassword: 'باید در ورود بعدی گذرواژه را عوض کند',
  systemAdmin: 'مدیر سامانه',
  systemAdminHelp:
    'مدیر سامانه همه‌ی مجوزهای سامانه‌ای را دارد، اما به محتوای اسناد دسترسی ندارد مگر از راه فهرست دسترسی.',
  manager: 'مدیر مستقیم',
  lastLogin: 'آخرین ورود',
  neverLoggedIn: 'هرگز',
  resetPassword: 'تعیین گذرواژه‌ی تازه',
  resetPasswordHelp: 'همه‌ی نشست‌های این کاربر پایان می‌یابد.',
  passwordReset: 'گذرواژه‌ی تازه تعیین شد.',
  deactivate: 'غیرفعال کردن',
  activate: 'فعال کردن',
  makeAdmin: 'مدیر سامانه شود',
  revokeAdmin: 'دیگر مدیر سامانه نباشد',
  memberOf: 'عضو گروه‌ها',
  holdsRoles: 'نقش‌ها',

  newGroup: 'گروه جدید',
  members: 'اعضا',
  addMember: 'افزودن عضو',
  groupInactiveHelp: 'گروه غیرفعال هیچ دسترسی‌ای به اعضایش نمی‌دهد.',

  newRole: 'نقش جدید',
  systemRole: 'نقش سامانه',
  rolePermissions: 'مجوزهای سامانه‌ای این نقش',
  rolePermissionsHelp: 'نقش فقط مجوزهای سامانه‌ای می‌دهد؛ دسترسی به اسناد از راه فهرست دسترسی پوشه‌ها و اسناد است.',
  holders: 'دارندگان نقش',
  addHolder: 'افزودن کاربر',

  newCategory: 'پوشه‌ی جدید',
  newSubcategory: 'زیرپوشه',
  move: 'جابه‌جایی',
  moveTo: 'انتقال به زیر',
  root: '(ریشه)',
  sortOrder: 'ترتیب',
  categoryInactiveHelp: 'در پوشه‌ی غیرفعال سند تازه ثبت نمی‌شود؛ اسناد موجود سر جایشان می‌مانند.',

  acl: 'فهرست دسترسی',
  why: 'چرا؟',
  subject: 'دارنده',
  subjectType: 'نوع دارنده',
  subjectTypes: { User: 'کاربر', Group: 'گروه', Role: 'نقش' } as Record<string, string>,
  permission: 'مجوز',
  effect: 'اثر',
  allow: 'اجازه',
  deny: 'منع',
  denyHelp: 'منع صریح همیشه بر هر اجازه‌ای برتری دارد، حتی اگر اجازه جزئی‌تر باشد.',
  inherit: 'به زیرپوشه‌ها و اسناد درونش هم برسد',
  reason: 'دلیل (اختیاری)',
  inheritedFrom: 'به ارث رسیده از',
  thisResource: 'همین‌جا',
  grant: 'افزودن دسترسی',
  grantFilingAccess: 'اعطای دسترسی ثبت سند (دیدن + ثبت)',
  filingNeedsViewAndCreate:
    'برای اینکه «ثبت سند» در رابط باز شود، هم «دیدن سند» و هم «ثبت سند» روی پوشه لازم است. دکمهٔ میان‌بر هر دو را با هم می‌دهد.',
  revoke: 'برداشتن',
  revokeInherited: 'این مورد را در همان پوشه‌ی بالاتر ویرایش کنید.',
  whyHelp: 'یک کاربر را انتخاب کنید تا ببینید هر کار را می‌تواند بکند یا نه، و چرا.',
  allowed: 'مجاز',
  denied: 'غیرمجاز',
  decidedBy: 'به سبب',

  changePassword: 'تغییر گذرواژه',
  mustChangeTitle: 'پیش از ادامه، گذرواژه‌ی تازه‌ای انتخاب کنید.',
  currentPassword: 'گذرواژه‌ی فعلی',
  newPassword: 'گذرواژه‌ی تازه',
  repeatPassword: 'تکرار گذرواژه‌ی تازه',
  passwordsDiffer: 'دو گذرواژه یکسان نیستند.',
  passwordChanged: 'گذرواژه عوض شد.',
};

/** Persian names for the permission catalog; the code stays visible for administrators. */
export const permissionLabels: Record<string, string> = {
  DOCUMENT_VIEW: 'دیدن سند',
  DOCUMENT_VIEW_DRAFT: 'دیدن پیش‌نویس‌ها',
  DOCUMENT_DOWNLOAD: 'دریافت فایل',
  DOCUMENT_PRINT: 'چاپ',
  DOCUMENT_CREATE: 'ثبت سند',
  DOCUMENT_EDIT: 'ویرایش مشخصات',
  DOCUMENT_DELETE: 'حذف (به سطل بازیافت)',
  DOCUMENT_RESTORE: 'بازگردانی',
  DOCUMENT_CREATE_VERSION: 'افزودن نسخه',
  DOCUMENT_SHARE: 'اشتراک با همکار',
  DOCUMENT_SHARE_EXTERNAL: 'پیوند بیرونی',
  DOCUMENT_MANAGE_PERMISSION: 'مدیریت دسترسی‌ها',
  DOCUMENT_EXPORT: 'خروجی گروهی',
  WORKFLOW_VIEW: 'دیدن گردش کار',
  WORKFLOW_APPROVE: 'تأیید در گردش کار',
  WORKFLOW_REJECT: 'رد در گردش کار',
  WORKFLOW_RETURN: 'بازگرداندن در گردش کار',
  WORKFLOW_REQUEST_CHANGES: 'درخواست اصلاح',
  AUDIT_VIEW: 'دیدن رویدادنگاری',
  AUDIT_EXPORT: 'خروجی رویدادنگاری',
  ADMIN_MANAGE_USERS: 'مدیریت کاربران',
  ADMIN_MANAGE_GROUPS: 'مدیریت گروه‌ها',
  ADMIN_MANAGE_ROLES: 'مدیریت نقش‌ها',
  ADMIN_MANAGE_DOCUMENT_TYPES: 'مدیریت انواع سند',
  ADMIN_MANAGE_WORKFLOWS: 'مدیریت گردش‌های کار',
  ADMIN_MANAGE_CATEGORIES: 'مدیریت پوشه‌ها',
  DOCUMENT_PURGE: 'حذف همیشگی اسناد',
  ADMIN_MANAGE_SEARCH: 'مدیریت جستجو',
};

export const permissionLabel = (code: string) => permissionLabels[code] ?? code;

/** Why the evaluator decided as it did, in words (section 5.4). */
export const reasonLabels: Record<string, string> = {
  AllowedByAcl: 'اجازه‌ی مستقیم',
  AllowedByInheritedAcl: 'اجازه‌ی به ارث رسیده',
  AllowedByShare: 'اشتراک',
  AllowedByWorkflowTask: 'کار باز در گردش کار',
  AllowedByAuthorship: 'نویسنده‌ی نسخه',
  AllowedBySystemRole: 'نقش سامانه‌ای',
  AllowedBySystemAdministrator: 'مدیر سامانه (با ثبت در رویدادنگاری)',
  DeniedByDefault: 'هیچ اجازه‌ای نیست',
  DeniedByExplicitDeny: 'منع صریح',
  DeniedUserInactive: 'کاربر غیرفعال است',
  DeniedResourceDeleted: 'در سطل بازیافت است',
  DeniedRequiresView: 'اجازه‌ی دیدن ندارد',
  DeniedDraft: 'پیش‌نویس است',
  DeniedScanIncomplete: 'بررسی ضدبدافزار تمام نشده',
  DeniedUnknownPermission: 'مجوز ناشناخته',
  DeniedWrongScope: 'مجوز سامانه‌ای است',
  DeniedUnknownResource: 'پیدا نشد',
};
