/** Persian copy for the disposition / Certificate of Destruction admin screen (phase 10.4). */
export const d = {
  menu: 'ابطال و امحا',
  title: 'بررسی ابطال و امحای رکورد',
  subtitle: 'رکوردهای منتظر امحا پس از پایان نگهداری؛ تخریب فقط پس از تأیید صریح.',
  empty: 'رکوردی در صف امحا نیست.',
  recordTitle: 'عنوان',
  status: 'وضعیت رکورد',
  retentionExpiry: 'پایان نگهداری',
  legalHold: 'نگهداری قانونی',
  onHold: 'فعال',
  notOnHold: 'ندارد',
  disposition: 'ابطال',
  noDisposition: 'بدون درخواست',
  finalVersion: 'نسخه‌ی نهایی',
  request: 'درخواست ابطال',
  approve: 'تأیید',
  reject: 'رد',
  destroy: 'امحا',
  viewCertificate: 'گواهی امحا',
  reason: 'دلیل',
  rejectionReason: 'دلیل رد',
  rejectionRequired: 'برای رد، دلیل الزامی است.',
  confirmDestroyTitle: 'تأیید نهایی امحا',
  confirmDestroyBody:
    'امحا برگشت‌ناپذیر است. محتوای فایل علامت حذف می‌گیرد، رکورد Destroyed می‌شود و گواهی امحا صادر می‌گردد.',
  confirmDestroyLabel: 'برای ادامه عبارت «امحا» را بنویسید',
  confirmDestroyWord: 'امحا',
  cancel: 'انصراف',
  close: 'بستن',
  submit: 'ثبت',
  certificateTitle: 'گواهی امحا',
  certificateNumber: 'شماره گواهی',
  contentHash: 'هش محتوا (SHA-256)',
  certificateHash: 'هش گواهی',
  approvedBy: 'تأییدکننده',
  approvedAt: 'زمان تأیید',
  destroyedBy: 'امحاکننده',
  destroyedAt: 'زمان امحا',
  legalHoldCheckedAt: 'آخرین بررسی نگهداری قانونی',
  retentionPolicy: 'سیاست نگهداری',
  auditHistory: 'سابقهٔ ممیزی ابطال',
  none: '—',
  pendingReview: 'در انتظار بررسی',
  approved: 'تأییدشده',
  rejected: 'ردشده',
  destroyed: 'امحاشده',
  requested: 'درخواست ثبت شد.',
  approvedOk: 'ابطال تأیید شد.',
  rejectedOk: 'ابطال رد شد؛ رکورد به Expired بازگشت.',
  destroyedOk: 'رکورد امحا شد و گواهی صادر گردید.',
  exportJson: 'خروجی JSON',
};
