/** Persian copy for the legacy import admin screen (phase 10.6). */
export const i = {
  menu: 'واردات میراثی',
  title: 'موتور واردات از سامانهٔ قدیمی',
  subtitle: 'مانیفست، اعتبارسنجی خشک، اجرا، ازسرگیری و گزارش — بدون دور زدن ACL یا رکورد.',
  create: 'ایجاد واردات',
  name: 'نام کار',
  sourceSystem: 'سامانهٔ مبدأ',
  manifest: 'مانیفست JSON',
  filesRootHint: 'ریشهٔ فایل‌ها فقط روی سرور (Dms:Import:FilesRoot) تنظیم می‌شود؛ اینجا زیرفolder نسبی اختیاری است.',
  relativeRoot: 'زیرفolder نسبی (اختیاری)',
  failurePolicy: 'سیاست خطا',
  continueOnError: 'ادامه با خطا',
  stopOnError: 'توقف با خطا',
  createCategories: 'ایجاد پوشه‌های مفقود',
  dryRunOnly: 'فقط اعتبارسنجی (بدون واردات)',
  validate: 'اعتبارسنجی',
  start: 'شروع واردات',
  pause: 'توقف موقت',
  resume: 'ازسرگیری',
  retry: 'تلاش مجدد خطاها',
  report: 'گزارش',
  refresh: 'بازخوانی',
  jobs: 'کارهای واردات',
  empty: 'هنوز کار وارداتی ثبت نشده است.',
  status: 'وضعیت',
  progress: 'پیشرفت',
  processed: 'پردازش‌شده',
  succeeded: 'موفق',
  failed: 'ناموفق',
  skipped: 'ردشده',
  invalid: 'نامعتبر',
  bytes: 'بایت',
  items: 'آیتم‌ها',
  filterStatus: 'فیلتر وضعیت',
  all: 'همه',
  sourceId: 'شناسه مبدأ',
  path: 'مسیر',
  error: 'خطا',
  validationTitle: 'گزارش اعتبارسنجی',
  warnings: 'هشدار',
  confirmStart: 'شروع واردات، اسناد و رکورد واقعی ایجاد می‌کند. ادامه می‌دهید؟',
  cancel: 'انصراف',
  submit: 'ثبت',
  close: 'بستن',
  downloadReport: 'دانلود JSON گزارش',
  selectJob: 'یک کار را از فهرست انتخاب کنید.',
};
