// <auto-generated />
using System;
using Dms.Sharing.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dms.Sharing.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SharingDbContext))]
    partial class SharingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("sharing")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Dms.Sharing.Domain.DocumentShare", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Message")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("message");

                    b.Property<short>("Permissions")
                        .HasColumnType("smallint")
                        .HasColumnName("permissions");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid?>("RevokedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("revoked_by");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid>("SharedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("shared_by");

                    b.Property<Guid>("SharedWith")
                        .HasColumnType("uuid")
                        .HasColumnName("shared_with_user_id");

                    b.Property<Guid>("VersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("version_id");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("ix_document_shares_document");

                    b.HasIndex("SharedWith", "DocumentId")
                        .HasDatabaseName("ix_document_shares_recipient")
                        .HasFilter("revoked_at IS NULL");

                    b.HasIndex("VersionId", "SharedWith")
                        .IsUnique()
                        .HasDatabaseName("ux_document_shares_version_recipient")
                        .HasFilter("revoked_at IS NULL");

                    b.ToTable("document_shares", "sharing", t =>
                        {
                            t.HasCheckConstraint("ck_document_shares_not_self", "shared_by <> shared_with_user_id");

                            t.HasCheckConstraint("ck_document_shares_permissions", "permissions BETWEEN 1 AND 7");

                            t.HasCheckConstraint("ck_document_shares_view", "(permissions & 1) = 1");
                        });
                });

            modelBuilder.Entity("Dms.Sharing.Domain.ShareLink", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_count");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("failed_attempts");

                    b.Property<string>("Label")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("label");

                    b.Property<DateTimeOffset?>("LastAccessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_accessed_at");

                    b.Property<DateTimeOffset?>("LockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until");

                    b.Property<int?>("MaxAccessCount")
                        .HasColumnType("integer")
                        .HasColumnName("max_access_count");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("password_hash");

                    b.Property<short>("Permissions")
                        .HasColumnType("smallint")
                        .HasColumnName("permissions");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid?>("RevokedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("revoked_by");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("token_hash");

                    b.Property<string>("TokenPrefix")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("token_prefix");

                    b.Property<Guid>("VersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("version_id");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("ix_share_links_document");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_share_links_token_hash");

                    b.ToTable("share_links", "sharing", t =>
                        {
                            t.HasCheckConstraint("ck_share_links_count", "access_count <= coalesce(max_access_count, access_count)");

                            t.HasCheckConstraint("ck_share_links_expiry", "expires_at > created_at");

                            t.HasCheckConstraint("ck_share_links_max_count", "max_access_count IS NULL OR max_access_count > 0");

                            t.HasCheckConstraint("ck_share_links_permissions", "permissions BETWEEN 1 AND 7");

                            t.HasCheckConstraint("ck_share_links_view", "(permissions & 1) = 1");
                        });
                });

            modelBuilder.Entity("Dms.Sharing.Domain.ShareLinkSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("LinkId")
                        .HasColumnType("uuid")
                        .HasColumnName("link_id");

                    b.Property<DateTimeOffset?>("PrintStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("print_started_at");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("token_hash");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_share_link_sessions_expires_at");

                    b.HasIndex("LinkId")
                        .HasDatabaseName("ix_share_link_sessions_link");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_share_link_sessions_token_hash");

                    b.ToTable("share_link_sessions", "sharing");
                });

            modelBuilder.Entity("Dms.Sharing.Domain.ShareLinkSession", b =>
                {
                    b.HasOne("Dms.Sharing.Domain.ShareLink", null)
                        .WithMany()
                        .HasForeignKey("LinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_share_link_sessions_link");
                });
#pragma warning restore 612, 618
        }
    }
}
