// <auto-generated />
using System;
using System.Collections.Generic;
using Dms.Workflow.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dms.Workflow.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(WorkflowDbContext))]
    partial class WorkflowDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("workflow")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Dms.Workflow.Domain.WorkflowDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid?>("LatestPublishedVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("latest_published_version_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_workflows_code");

                    b.ToTable("workflows", "workflow");
                });

            modelBuilder.Entity("Dms.Workflow.Domain.WorkflowDefinitionVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<Guid?>("PublishedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("published_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowId")
                        .IsUnique()
                        .HasDatabaseName("ux_workflow_versions_single_draft")
                        .HasFilter("status = 'Draft'");

                    b.HasIndex("WorkflowId", "VersionNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_workflow_versions_number");

                    b.ToTable("workflow_versions", "workflow");
                });

            modelBuilder.Entity("Dms.Workflow.Domain.WorkflowInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AttentionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("attention_reason");

                    b.Property<string>("CancelReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("cancel_reason");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<int>("CurrentSequence")
                        .HasColumnType("integer")
                        .HasColumnName("current_sequence");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<Guid>("DocumentVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_version_id");

                    b.Property<int>("Round")
                        .HasColumnType("integer")
                        .HasColumnName("round");

                    b.PrimitiveCollection<List<string>>("SkippedSteps")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("skipped_steps");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<Guid>("StartedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("started_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("status");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<long>("VersionSortKey")
                        .HasColumnType("bigint")
                        .HasColumnName("version_sort_key");

                    b.Property<Guid>("WorkflowVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_version_id");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("ix_workflow_instances_document");

                    b.HasIndex("DocumentVersionId")
                        .IsUnique()
                        .HasDatabaseName("ux_workflow_instances_running_version")
                        .HasFilter("status = 'Running'");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_workflow_instances_status");

                    b.HasIndex("WorkflowVersionId");

                    b.ToTable("workflow_instances", "workflow");
                });

            modelBuilder.Entity("Dms.Workflow.Domain.WorkflowStepDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Actions")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("actions");

                    b.Property<bool>("AllowSelfApproval")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_self_approval");

                    b.Property<string>("AssigneeFieldCode")
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)")
                        .HasColumnName("assignee_field_code");

                    b.Property<Guid?>("AssigneeId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignee_id");

                    b.Property<string>("AssigneeType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("assignee_type");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)")
                        .HasColumnName("code");

                    b.Property<string>("CompletionRule")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("completion_rule");

                    b.Property<string>("Condition")
                        .HasColumnType("jsonb")
                        .HasColumnName("condition");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<int?>("SlaHours")
                        .HasColumnType("integer")
                        .HasColumnName("sla_hours");

                    b.Property<Guid>("WorkflowVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_version_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowVersionId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ux_workflow_steps_code");

                    b.HasIndex("WorkflowVersionId", "Sequence")
                        .HasDatabaseName("ix_workflow_steps_sequence");

                    b.ToTable("workflow_steps", "workflow", t =>
                        {
                            t.HasCheckConstraint("ck_workflow_steps_assignee", "(assignee_type IN ('User','Group','Role')) = (assignee_id IS NOT NULL) AND (assignee_type = 'DynamicUserField') = (assignee_field_code IS NOT NULL)");

                            t.HasCheckConstraint("ck_workflow_steps_sequence", "sequence BETWEEN 1 AND 1000");
                        });
                });

            modelBuilder.Entity("Dms.Workflow.Domain.WorkflowTask", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("action");

                    b.Property<Guid?>("AssignedGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_group_id");

                    b.Property<Guid?>("AssignedRoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_role_id");

                    b.Property<Guid?>("AssignedUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_user_id");

                    b.Property<string>("Comment")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("comment");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<Guid?>("CompletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("completed_by");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DueAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_at");

                    b.Property<Guid?>("ForwardedFromTaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("forwarded_from_task_id");

                    b.Property<Guid>("InstanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("instance_id");

                    b.Property<DateTimeOffset?>("OverdueNotifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("overdue_notified_at");

                    b.Property<int>("Round")
                        .HasColumnType("integer")
                        .HasColumnName("round");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("StepCode")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)")
                        .HasColumnName("step_code");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("AssignedGroupId")
                        .HasDatabaseName("ix_workflow_tasks_group")
                        .HasFilter("status = 'Pending'");

                    b.HasIndex("AssignedRoleId")
                        .HasDatabaseName("ix_workflow_tasks_role")
                        .HasFilter("status = 'Pending'");

                    b.HasIndex("AssignedUserId")
                        .HasDatabaseName("ix_workflow_tasks_user")
                        .HasFilter("status = 'Pending'");

                    b.HasIndex("DueAt")
                        .HasDatabaseName("ix_workflow_tasks_due")
                        .HasFilter("status = 'Pending'");

                    b.HasIndex("InstanceId")
                        .HasDatabaseName("ix_workflow_tasks_instance");

                    b.ToTable("workflow_tasks", "workflow", t =>
                        {
                            t.HasCheckConstraint("ck_workflow_tasks_one_assignee", "num_nonnulls(assigned_user_id, assigned_group_id, assigned_role_id) = 1");
                        });
                });

            modelBuilder.Entity("Dms.Workflow.Domain.WorkflowDefinitionVersion", b =>
                {
                    b.HasOne("Dms.Workflow.Domain.WorkflowDefinition", null)
                        .WithMany("Versions")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dms.Workflow.Domain.WorkflowInstance", b =>
                {
                    b.HasOne("Dms.Workflow.Domain.WorkflowDefinitionVersion", null)
                        .WithMany()
                        .HasForeignKey("WorkflowVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_instances_workflow_version");
                });

            modelBuilder.Entity("Dms.Workflow.Domain.WorkflowStepDefinition", b =>
                {
                    b.HasOne("Dms.Workflow.Domain.WorkflowDefinitionVersion", null)
                        .WithMany("Steps")
                        .HasForeignKey("WorkflowVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_steps_version");
                });

            modelBuilder.Entity("Dms.Workflow.Domain.WorkflowTask", b =>
                {
                    b.HasOne("Dms.Workflow.Domain.WorkflowInstance", null)
                        .WithMany("Tasks")
                        .HasForeignKey("InstanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_tasks_instance");
                });

            modelBuilder.Entity("Dms.Workflow.Domain.WorkflowDefinition", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("Dms.Workflow.Domain.WorkflowDefinitionVersion", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("Dms.Workflow.Domain.WorkflowInstance", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
