// <auto-generated />
using System;
using Dms.Storage.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dms.Storage.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(StorageDbContext))]
    [Migration("20260923235503_AddRenditions")]
    partial class AddRenditions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("storage")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Dms.Storage.Domain.Rendition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Error")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("error");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("kind");

                    b.Property<Guid>("SourceObjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_object_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("SourceObjectId", "Kind")
                        .IsUnique()
                        .HasDatabaseName("ux_renditions_source_kind");

                    b.ToTable("renditions", "storage");
                });

            modelBuilder.Entity("Dms.Storage.Domain.RenditionPage", b =>
                {
                    b.Property<Guid>("RenditionId")
                        .HasColumnType("uuid")
                        .HasColumnName("rendition_id");

                    b.Property<int>("PageNumber")
                        .HasColumnType("integer")
                        .HasColumnName("page_number");

                    b.Property<Guid>("ObjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("object_id");

                    b.HasKey("RenditionId", "PageNumber");

                    b.HasIndex("ObjectId");

                    b.ToTable("rendition_pages", "storage");
                });

            modelBuilder.Entity("Dms.Storage.Domain.StorageObject", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Bucket")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("bucket");

                    b.Property<DateTimeOffset?>("CommittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("committed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("DeclaredMimeType")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("declared_mime_type");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DetectedMimeType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("detected_mime_type");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("object_key");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("original_file_name");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("provider");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("purpose");

                    b.Property<string>("ScanStatus")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("scan_status");

                    b.Property<DateTimeOffset?>("ScannedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scanned_at");

                    b.Property<byte[]>("Sha256")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("sha256");

                    b.Property<long>("Size")
                        .HasColumnType("bigint")
                        .HasColumnName("size");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("status");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_storage_objects_staged")
                        .HasFilter("status = 'Staged'");

                    b.HasIndex("Sha256")
                        .HasDatabaseName("ix_storage_objects_sha256");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_storage_objects_pending_deletion")
                        .HasFilter("status = 'PendingDeletion'");

                    b.HasIndex("Provider", "Bucket", "ObjectKey")
                        .IsUnique()
                        .HasDatabaseName("ux_storage_objects_key");

                    b.ToTable("storage_objects", "storage", t =>
                        {
                            t.HasCheckConstraint("ck_storage_objects_sha256", "octet_length(sha256) = 32");

                            t.HasCheckConstraint("ck_storage_objects_size", "size >= 0");
                        });
                });

            modelBuilder.Entity("Dms.Storage.Domain.Rendition", b =>
                {
                    b.HasOne("Dms.Storage.Domain.StorageObject", null)
                        .WithMany()
                        .HasForeignKey("SourceObjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_renditions_source");
                });

            modelBuilder.Entity("Dms.Storage.Domain.RenditionPage", b =>
                {
                    b.HasOne("Dms.Storage.Domain.StorageObject", null)
                        .WithMany()
                        .HasForeignKey("ObjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_rendition_pages_object");

                    b.HasOne("Dms.Storage.Domain.Rendition", null)
                        .WithMany("Pages")
                        .HasForeignKey("RenditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rendition_pages_rendition");
                });

            modelBuilder.Entity("Dms.Storage.Domain.Rendition", b =>
                {
                    b.Navigation("Pages");
                });
#pragma warning restore 612, 618
        }
    }
}
